version: '3'

services:

### Mysql Container #######################################
  mysql:
    image: mysql:5.7
    volumes:
        - ../data/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=haha77697ahbdka9
      - MYSQL_DATABASE=data
    restart: always
    cap_add: [ SYS_NICE ]

### Nginx Server Container ##################################
  nginx:
    build:
      context: ./nginx
    volumes:
        - ${WEB_ROOT}:/var/www/html
    ports:
        - "${NGINX_HTTP_PORT}:80"
        - "${NGINX_HTTPS_PORT}:443"
    depends_on:
        - node
    restart: always

### Node Container ##################################

  node:
    build:
      context: ./node
    volumes:
        - ${WEB_ROOT}:/var/www/html
    restart: always
### PHPMyAdmin Container #########################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: always
    depends_on:
        - mysql
    environment:
      - PMA_HOST=mysql
### Volumes Setup ###########################################
networks:
  default:
    external:
      name: ${USER_NETWORK}
